export const allproductsData = {
  hushinSilver: {
    stockText: "Currently in stock. Ships Today",
    description: [
      "Hush isn’t just a speaker—it’s an approach to sound. Inspired by our ethos of attentive listening, it’s designed for spaces where music is meant to be experienced with intention.",
      "At SILENCE PLEASE, we believe sound should be felt, not forced—a presence that enhances rather than overwhelms. The Hush 4” studio monitors are tuned for clarity, warmth, and precision, unearthing subtleties in every recording. From the layered textures of electronic music to the stillness of ambient compositions, Hush captures what conventional speakers often lose.",
      "Compact in Form, Expansive in Sound...",
      "Small in scale yet powerful in delivery, Hush is designed to bring rich, immersive sound to modern living spaces. Perfectly sized for a New York apartment yet refined enough for any environment, it delivers a full, natural sound field without demanding space.",
    ],
    specs: [
      "Speaker Use: Bookshelf",
      "Speaker Type: Passive",
      'Mid/Woofer: 4"',
      'Tweeter: 1"',
      "Overall Frequency: 65Hz – 20kHz (-6 dB)",
      "Crossover: 2-way",
      "Lower: -3 dB limit 65Hz",
      "Upper: -3 dB limit 20kHz",
      "Nominal Impedance: 4 ohm / Working 4–8 ohm",
      "Recommended Watts/Channel: 35W",
      "Efficiency: 87 dB",
      "Inputs: Terminal post",
      "Maximum Power Handling: 55W",
    ],
    dimensions: [
      "Product Size: L18 x W18 x H38 cm",
      "Shipping Unit: Pair",
      "Product Unit Weight: 3.8 kg",
      "Package Dimensions: L60.5 x W50.5 x H31 cm",
    ],
    warranty: "1 year manufacturer warranty",
  },

  hushinMatteBlack: {
    stockText: "Currently in stock. Ships Today",
    description: [
      "Hush isn’t just a speaker—it’s an approach to sound. Inspired by our ethos of attentive listening, it’s designed for spaces where music is meant to be experienced with intention.",
      "At SILENCE PLEASE, we believe sound should be felt, not forced—a presence that enhances rather than overwhelms. The Hush 4” studio monitors are tuned for clarity, warmth, and precision, unearthing subtleties in every recording. From the layered textures of electronic music to the stillness of ambient compositions, Hush captures what conventional speakers often lose.",
      "Compact in Form, Expansive in Sound...",
      "Small in scale yet powerful in delivery, Hush is designed to bring rich, immersive sound to modern living spaces. Perfectly sized for a New York apartment yet refined enough for any environment, it delivers a full, natural sound field without demanding space.",
    ],
    specs: [
      "Speaker Use: Bookshelf",
      "Speaker Type: Passive",
      'Mid/Woofer: 4"',
      'Tweeter: 1"',
      "Overall Frequency: 65Hz – 20kHz (-6 dB)",
      "Crossover: 2-way",
      "Lower: -3 dB limit 65Hz",
      "Upper: -3 dB limit 20kHz",
      "Nominal Impedance: 4 ohm / Working 4–8 ohm",
      "Recommended Watts/Channel: 35W",
      "Efficiency: 87 dB",
      "Inputs: Terminal post",
      "Maximum Power Handling: 55W",
    ],
    dimensions: [
      "Product Size: L18 x W18 x H38 cm",
      "Shipping Unit: Pair",
      "Product Unit Weight: 3.8 kg",
      "Package Dimensions: L60.5 x W50.5 x H31 cm",
    ],
    warranty: "1 year manufacturer warranty",
  },

  hushinMetalliGray: {
    stockText: "Currently in stock. Ships Today",
    description: [
      "Hush isn’t just a speaker—it’s an approach to sound. Inspired by our ethos of attentive listening, it’s designed for spaces where music is meant to be experienced with intention.",
      "At SILENCE PLEASE, we believe sound should be felt, not forced—a presence that enhances rather than overwhelms. The Hush 4” studio monitors are tuned for clarity, warmth, and precision, unearthing subtleties in every recording. From the layered textures of electronic music to the stillness of ambient compositions, Hush captures what conventional speakers often lose.",
      "Compact in Form, Expansive in Sound...",
      "Small in scale yet powerful in delivery, Hush is designed to bring rich, immersive sound to modern living spaces. Perfectly sized for a New York apartment yet refined enough for any environment, it delivers a full, natural sound field without demanding space.",
    ],
    specs: [
      "Speaker Use: Bookshelf",
      "Speaker Type: Passive",
      'Mid/Woofer: 4"',
      'Tweeter: 1"',
      "Overall Frequency: 65Hz – 20kHz (-6 dB)",
      "Crossover: 2-way",
      "Lower: -3 dB limit 65Hz",
      "Upper: -3 dB limit 20kHz",
      "Nominal Impedance: 4 ohm / Working 4–8 ohm",
      "Recommended Watts/Channel: 35W",
      "Efficiency: 87 dB",
      "Inputs: Terminal post",
      "Maximum Power Handling: 55W",
    ],
    dimensions: [
      "Product Size: L18 x W18 x H38 cm",
      "Shipping Unit: Pair",
      "Product Unit Weight: 3.8 kg",
      "Package Dimensions: L60.5 x W50.5 x H31 cm",
    ],
    warranty: "1 year manufacturer warranty",
  },

  hushinWhite: {
    stockText: "Currently in stock. Ships Today",
    description: [
      "Hush isn’t just a speaker—it’s an approach to sound. Inspired by our ethos of attentive listening, it’s designed for spaces where music is meant to be experienced with intention.",
      "At SILENCE PLEASE, we believe sound should be felt, not forced—a presence that enhances rather than overwhelms. The Hush 4” studio monitors are tuned for clarity, warmth, and precision, unearthing subtleties in every recording. From the layered textures of electronic music to the stillness of ambient compositions, Hush captures what conventional speakers often lose.",
      "Compact in Form, Expansive in Sound...",
      "Small in scale yet powerful in delivery, Hush is designed to bring rich, immersive sound to modern living spaces. Perfectly sized for a New York apartment yet refined enough for any environment, it delivers a full, natural sound field without demanding space.",
    ],
    specs: [
      "Speaker Use: Bookshelf",
      "Speaker Type: Passive",
      'Mid/Woofer: 4"',
      'Tweeter: 1"',
      "Overall Frequency: 65Hz – 20kHz (-6 dB)",
      "Crossover: 2-way",
      "Lower: -3 dB limit 65Hz",
      "Upper: -3 dB limit 20kHz",
      "Nominal Impedance: 4 ohm / Working 4–8 ohm",
      "Recommended Watts/Channel: 35W",
      "Efficiency: 87 dB",
      "Inputs: Terminal post",
      "Maximum Power Handling: 55W",
    ],
    dimensions: [
      "Product Size: L18 x W18 x H38 cm",
      "Shipping Unit: Pair",
      "Product Unit Weight: 3.8 kg",
      "Package Dimensions: L60.5 x W50.5 x H31 cm",
    ],
    warranty: "1 year manufacturer warranty",
  },

  hushinGreen: {
    stockText: "Currently in stock. Ships Today",
    description: [
      "Hush isn’t just a speaker—it’s an approach to sound. Inspired by our ethos of attentive listening, it’s designed for spaces where music is meant to be experienced with intention.",
      "At SILENCE PLEASE, we believe sound should be felt, not forced—a presence that enhances rather than overwhelms. The Hush 4” studio monitors are tuned for clarity, warmth, and precision, unearthing subtleties in every recording. From the layered textures of electronic music to the stillness of ambient compositions, Hush captures what conventional speakers often lose.",
      "Compact in Form, Expansive in Sound...",
      "Small in scale yet powerful in delivery, Hush is designed to bring rich, immersive sound to modern living spaces. Perfectly sized for a New York apartment yet refined enough for any environment, it delivers a full, natural sound field without demanding space.",
    ],
    specs: [
      "Speaker Use: Bookshelf",
      "Speaker Type: Passive",
      'Mid/Woofer: 4"',
      'Tweeter: 1"',
      "Overall Frequency: 65Hz – 20kHz (-6 dB)",
      "Crossover: 2-way",
      "Lower: -3 dB limit 65Hz",
      "Upper: -3 dB limit 20kHz",
      "Nominal Impedance: 4 ohm / Working 4–8 ohm",
      "Recommended Watts/Channel: 35W",
      "Efficiency: 87 dB",
      "Inputs: Terminal post",
      "Maximum Power Handling: 55W",
    ],
    dimensions: [
      "Product Size: L18 x W18 x H38 cm",
      "Shipping Unit: Pair",
      "Product Unit Weight: 3.8 kg",
      "Package Dimensions: L60.5 x W50.5 x H31 cm",
    ],
    warranty: "1 year manufacturer warranty",
  },

  hushinGlossyBlack: {
    stockText: "Currently in stock. Ships Today",
    description: [
      "Hush isn’t just a speaker—it’s an approach to sound. Inspired by our ethos of attentive listening, it’s designed for spaces where music is meant to be experienced with intention.",
      "At SILENCE PLEASE, we believe sound should be felt, not forced—a presence that enhances rather than overwhelms. The Hush 4” studio monitors are tuned for clarity, warmth, and precision, unearthing subtleties in every recording. From the layered textures of electronic music to the stillness of ambient compositions, Hush captures what conventional speakers often lose.",
      "Compact in Form, Expansive in Sound...",
      "Small in scale yet powerful in delivery, Hush is designed to bring rich, immersive sound to modern living spaces. Perfectly sized for a New York apartment yet refined enough for any environment, it delivers a full, natural sound field without demanding space.",
    ],
    specs: [
      "Speaker Use: Bookshelf",
      "Speaker Type: Passive",
      'Mid/Woofer: 4"',
      'Tweeter: 1"',
      "Overall Frequency: 65Hz – 20kHz (-6 dB)",
      "Crossover: 2-way",
      "Lower: -3 dB limit 65Hz",
      "Upper: -3 dB limit 20kHz",
      "Nominal Impedance: 4 ohm / Working 4–8 ohm",
      "Recommended Watts/Channel: 35W",
      "Efficiency: 87 dB",
      "Inputs: Terminal post",
      "Maximum Power Handling: 55W",
    ],
    dimensions: [
      "Product Size: L18 x W18 x H38 cm",
      "Shipping Unit: Pair",
      "Product Unit Weight: 3.8 kg",
      "Package Dimensions: L60.5 x W50.5 x H31 cm",
    ],
    warranty: "1 year manufacturer warranty",
  },

  speakersCables: {
    stockText: "Currently in stock. Ships Today",
    description: [
      "Hush isn’t just a speaker—it’s an approach to sound. Inspired by our ethos of attentive listening, it’s designed for spaces where music is meant to be experienced with intention.",
      "At SILENCE PLEASE, we believe sound should be felt, not forced—a presence that enhances rather than overwhelms. The Hush 4” studio monitors are tuned for clarity, warmth, and precision, unearthing subtleties in every recording. From the layered textures of electronic music to the stillness of ambient compositions, Hush captures what conventional speakers often lose.",
      "Compact in Form, Expansive in Sound...",
      "Small in scale yet powerful in delivery, Hush is designed to bring rich, immersive sound to modern living spaces. Perfectly sized for a New York apartment yet refined enough for any environment, it delivers a full, natural sound field without demanding space.",
    ],
    specs: [
      "Speaker Use: Bookshelf",
      "Speaker Type: Passive",
      'Mid/Woofer: 4"',
      'Tweeter: 1"',
      "Overall Frequency: 65Hz – 20kHz (-6 dB)",
      "Crossover: 2-way",
      "Lower: -3 dB limit 65Hz",
      "Upper: -3 dB limit 20kHz",
      "Nominal Impedance: 4 ohm / Working 4–8 ohm",
      "Recommended Watts/Channel: 35W",
      "Efficiency: 87 dB",
      "Inputs: Terminal post",
      "Maximum Power Handling: 55W",
    ],
    dimensions: [
      "Product Size: L18 x W18 x H38 cm",
      "Shipping Unit: Pair",
      "Product Unit Weight: 3.8 kg",
      "Package Dimensions: L60.5 x W50.5 x H31 cm",
    ],
    warranty: "1 year manufacturer warranty",
  },

  glowel34SetTubeamp: {
    stockText: "Currently in stock. Ships Today",
    description: [
      "Hush isn’t just a speaker—it’s an approach to sound. Inspired by our ethos of attentive listening, it’s designed for spaces where music is meant to be experienced with intention.",
      "At SILENCE PLEASE, we believe sound should be felt, not forced—a presence that enhances rather than overwhelms. The Hush 4” studio monitors are tuned for clarity, warmth, and precision, unearthing subtleties in every recording. From the layered textures of electronic music to the stillness of ambient compositions, Hush captures what conventional speakers often lose.",
      "Compact in Form, Expansive in Sound...",
      "Small in scale yet powerful in delivery, Hush is designed to bring rich, immersive sound to modern living spaces. Perfectly sized for a New York apartment yet refined enough for any environment, it delivers a full, natural sound field without demanding space.",
    ],
    specs: [
      "Speaker Use: Bookshelf",
      "Speaker Type: Passive",
      'Mid/Woofer: 4"',
      'Tweeter: 1"',
      "Overall Frequency: 65Hz – 20kHz (-6 dB)",
      "Crossover: 2-way",
      "Lower: -3 dB limit 65Hz",
      "Upper: -3 dB limit 20kHz",
      "Nominal Impedance: 4 ohm / Working 4–8 ohm",
      "Recommended Watts/Channel: 35W",
      "Efficiency: 87 dB",
      "Inputs: Terminal post",
      "Maximum Power Handling: 55W",
    ],
    dimensions: [
      "Product Size: L18 x W18 x H38 cm",
      "Shipping Unit: Pair",
      "Product Unit Weight: 3.8 kg",
      "Package Dimensions: L60.5 x W50.5 x H31 cm",
    ],
    warranty: "1 year manufacturer warranty",
  },

  echo: {
    stockText: "Currently in stock. Ships Today",
    description: [
      "Hush isn’t just a speaker—it’s an approach to sound. Inspired by our ethos of attentive listening, it’s designed for spaces where music is meant to be experienced with intention.",
      "At SILENCE PLEASE, we believe sound should be felt, not forced—a presence that enhances rather than overwhelms. The Hush 4” studio monitors are tuned for clarity, warmth, and precision, unearthing subtleties in every recording. From the layered textures of electronic music to the stillness of ambient compositions, Hush captures what conventional speakers often lose.",
      "Compact in Form, Expansive in Sound...",
      "Small in scale yet powerful in delivery, Hush is designed to bring rich, immersive sound to modern living spaces. Perfectly sized for a New York apartment yet refined enough for any environment, it delivers a full, natural sound field without demanding space.",
    ],
    specs: [
      "Speaker Use: Bookshelf",
      "Speaker Type: Passive",
      'Mid/Woofer: 4"',
      'Tweeter: 1"',
      "Overall Frequency: 65Hz – 20kHz (-6 dB)",
      "Crossover: 2-way",
      "Lower: -3 dB limit 65Hz",
      "Upper: -3 dB limit 20kHz",
      "Nominal Impedance: 4 ohm / Working 4–8 ohm",
      "Recommended Watts/Channel: 35W",
      "Efficiency: 87 dB",
      "Inputs: Terminal post",
      "Maximum Power Handling: 55W",
    ],
    dimensions: [
      "Product Size: L18 x W18 x H38 cm",
      "Shipping Unit: Pair",
      "Product Unit Weight: 3.8 kg",
      "Package Dimensions: L60.5 x W50.5 x H31 cm",
    ],
    warranty: "1 year manufacturer warranty",
  },

  huminBrushAluminum: {
    stockText: "Currently in stock. Ships Today",
    description: [
      "Hush isn’t just a speaker—it’s an approach to sound. Inspired by our ethos of attentive listening, it’s designed for spaces where music is meant to be experienced with intention.",
      "At SILENCE PLEASE, we believe sound should be felt, not forced—a presence that enhances rather than overwhelms. The Hush 4” studio monitors are tuned for clarity, warmth, and precision, unearthing subtleties in every recording. From the layered textures of electronic music to the stillness of ambient compositions, Hush captures what conventional speakers often lose.",
      "Compact in Form, Expansive in Sound...",
      "Small in scale yet powerful in delivery, Hush is designed to bring rich, immersive sound to modern living spaces. Perfectly sized for a New York apartment yet refined enough for any environment, it delivers a full, natural sound field without demanding space.",
    ],
    specs: [
      "Speaker Use: Bookshelf",
      "Speaker Type: Passive",
      'Mid/Woofer: 4"',
      'Tweeter: 1"',
      "Overall Frequency: 65Hz – 20kHz (-6 dB)",
      "Crossover: 2-way",
      "Lower: -3 dB limit 65Hz",
      "Upper: -3 dB limit 20kHz",
      "Nominal Impedance: 4 ohm / Working 4–8 ohm",
      "Recommended Watts/Channel: 35W",
      "Efficiency: 87 dB",
      "Inputs: Terminal post",
      "Maximum Power Handling: 55W",
    ],
    dimensions: [
      "Product Size: L18 x W18 x H38 cm",
      "Shipping Unit: Pair",
      "Product Unit Weight: 3.8 kg",
      "Package Dimensions: L60.5 x W50.5 x H31 cm",
    ],
    warranty: "1 year manufacturer warranty",
  },

  hushinWhiteoak: {
    stockText: "Currently in stock. Ships Today",
    description: [
      "Hush isn’t just a speaker—it’s an approach to sound. Inspired by our ethos of attentive listening, it’s designed for spaces where music is meant to be experienced with intention.",
      "At SILENCE PLEASE, we believe sound should be felt, not forced—a presence that enhances rather than overwhelms. The Hush 4” studio monitors are tuned for clarity, warmth, and precision, unearthing subtleties in every recording. From the layered textures of electronic music to the stillness of ambient compositions, Hush captures what conventional speakers often lose.",
      "Compact in Form, Expansive in Sound...",
      "Small in scale yet powerful in delivery, Hush is designed to bring rich, immersive sound to modern living spaces. Perfectly sized for a New York apartment yet refined enough for any environment, it delivers a full, natural sound field without demanding space.",
    ],
    specs: [
      "Speaker Use: Bookshelf",
      "Speaker Type: Passive",
      'Mid/Woofer: 4"',
      'Tweeter: 1"',
      "Overall Frequency: 65Hz – 20kHz (-6 dB)",
      "Crossover: 2-way",
      "Lower: -3 dB limit 65Hz",
      "Upper: -3 dB limit 20kHz",
      "Nominal Impedance: 4 ohm / Working 4–8 ohm",
      "Recommended Watts/Channel: 35W",
      "Efficiency: 87 dB",
      "Inputs: Terminal post",
      "Maximum Power Handling: 55W",
    ],
    dimensions: [
      "Product Size: L18 x W18 x H38 cm",
      "Shipping Unit: Pair",
      "Product Unit Weight: 3.8 kg",
      "Package Dimensions: L60.5 x W50.5 x H31 cm",
    ],
    warranty: "1 year manufacturer warranty",
  },

  hushinWalnut: {
    stockText: "Currently in stock. Ships Today",
    description: [
      "Hush isn’t just a speaker—it’s an approach to sound. Inspired by our ethos of attentive listening, it’s designed for spaces where music is meant to be experienced with intention.",
      "At SILENCE PLEASE, we believe sound should be felt, not forced—a presence that enhances rather than overwhelms. The Hush 4” studio monitors are tuned for clarity, warmth, and precision, unearthing subtleties in every recording. From the layered textures of electronic music to the stillness of ambient compositions, Hush captures what conventional speakers often lose.",
      "Compact in Form, Expansive in Sound...",
      "Small in scale yet powerful in delivery, Hush is designed to bring rich, immersive sound to modern living spaces. Perfectly sized for a New York apartment yet refined enough for any environment, it delivers a full, natural sound field without demanding space.",
    ],
    specs: [
      "Speaker Use: Bookshelf",
      "Speaker Type: Passive",
      'Mid/Woofer: 4"',
      'Tweeter: 1"',
      "Overall Frequency: 65Hz – 20kHz (-6 dB)",
      "Crossover: 2-way",
      "Lower: -3 dB limit 65Hz",
      "Upper: -3 dB limit 20kHz",
      "Nominal Impedance: 4 ohm / Working 4–8 ohm",
      "Recommended Watts/Channel: 35W",
      "Efficiency: 87 dB",
      "Inputs: Terminal post",
      "Maximum Power Handling: 55W",
    ],
    dimensions: [
      "Product Size: L18 x W18 x H38 cm",
      "Shipping Unit: Pair",
      "Product Unit Weight: 3.8 kg",
      "Package Dimensions: L60.5 x W50.5 x H31 cm",
    ],
    warranty: "1 year manufacturer warranty",
  },

  huminGreenEdgeplexiglass: {
    stockText: "Currently in stock. Ships Today",
    description: [
      "Hush isn’t just a speaker—it’s an approach to sound. Inspired by our ethos of attentive listening, it’s designed for spaces where music is meant to be experienced with intention.",
      "At SILENCE PLEASE, we believe sound should be felt, not forced—a presence that enhances rather than overwhelms. The Hush 4” studio monitors are tuned for clarity, warmth, and precision, unearthing subtleties in every recording. From the layered textures of electronic music to the stillness of ambient compositions, Hush captures what conventional speakers often lose.",
      "Compact in Form, Expansive in Sound...",
      "Small in scale yet powerful in delivery, Hush is designed to bring rich, immersive sound to modern living spaces. Perfectly sized for a New York apartment yet refined enough for any environment, it delivers a full, natural sound field without demanding space.",
    ],
    specs: [
      "Speaker Use: Bookshelf",
      "Speaker Type: Passive",
      'Mid/Woofer: 4"',
      'Tweeter: 1"',
      "Overall Frequency: 65Hz – 20kHz (-6 dB)",
      "Crossover: 2-way",
      "Lower: -3 dB limit 65Hz",
      "Upper: -3 dB limit 20kHz",
      "Nominal Impedance: 4 ohm / Working 4–8 ohm",
      "Recommended Watts/Channel: 35W",
      "Efficiency: 87 dB",
      "Inputs: Terminal post",
      "Maximum Power Handling: 55W",
    ],
    dimensions: [
      "Product Size: L18 x W18 x H38 cm",
      "Shipping Unit: Pair",
      "Product Unit Weight: 3.8 kg",
      "Package Dimensions: L60.5 x W50.5 x H31 cm",
    ],
    warranty: "1 year manufacturer warranty",
  },

  whisper: {
    stockText: "Currently in stock. Ships Today",
    description: [
      "A statement of controlled power. The Whisper is a 3-way high-fidelity speaker built for those who crave the energy of club systems, but with more intentional scale. Outfitted with 12-inch drivers and refined horn geometry, it delivers immersive sound with nuance, clarity, and weight without overwhelming the room.",
      "Sized between intimacy and intensity to deliver precision with a punch, The Whisper is perfect for studios, listening rooms, and large living spaces that require full-spectrum detail and presence but without going full Roar.",
    ],
    specs: [
      "Speaker Use: Bookshelf",
      "Speaker Type: Passive",
      'Mid/Woofer: 4"',
      'Tweeter: 1"',
      "Overall Frequency: 65Hz – 20kHz (-6 dB)",
      "Crossover: 2-way",
      "Lower: -3 dB limit 65Hz",
      "Upper: -3 dB limit 20kHz",
      "Nominal Impedance: 4 ohm / Working 4–8 ohm",
      "Recommended Watts/Channel: 35W",
      "Efficiency: 87 dB",
      "Inputs: Terminal post",
      "Maximum Power Handling: 55W",
    ],
    dimensions: [
      "Product Size: L18 x W18 x H38 cm",
      "Shipping Unit: Pair",
      "Product Unit Weight: 3.8 kg",
      "Package Dimensions: L60.5 x W50.5 x H31 cm",
    ],
    warranty: "1 year manufacturer warranty",
  },

  roar: {
    stockText: "Pickup available at Silence Please",
    description: [
      "The Roar",
      "A sculpted force for serious listening.",
      "Compact in Form, Expansive in Sound...",
      "The Roar is a 3-way passive loudspeaker engineered for high-energy sound systems that demand both presence and precision. Outfitted with the powerful 15-inch woofers and high-performance compression drivers, it delivers visceral low-end, articulate mids, and crystal-clear highs—without compromise.",
      "Built for large rooms, studios, and performance environments, The Roar brings club-scale impact with audiophile detail. It doesn’t just play loud—it plays with control, weight, and intent.",
      "General specss",
      "Type: 3‑Way Passive Full-Range Loudspeaker",
      "Dimensions H: 51 7/12″ W: 29 5/6″ D: 19 4/9″",
      "Configuration",
      "- Woofer: 15 (15″, 8 Ω, 700 W AES / 1,400 W program, 98 dB, 30 Hz–1.5 kHz, ±9 mm Xmax)",
      "- Midrange: 5″ compression driver (horn-loaded)",
      "- High: 1.75″ compression driver (horn-loaded)",
      "Acoustic Performance",
      "- Frequency Response: ~30 Hz – 20 kHz (±3 dB)",
      "- Max SPL @ 600 W AES: ~125 dB (driven by the woofer’s 700 W AES capability)",
      "Impedance: 8 Ω nominal",
      "- Crossover Points: 600 Hz / 6 kHz",
      "- Sensitivity: LF ~98 dB, MF ~108 dB, HF ~109 dB",
    ],
    warranty: "1 year manufacturer warranty",
  },

  thunder: {
    stockText: "Thunder: Large-Format 3-Way Horn Loudspeaker",
    description: [
      "Thunder is a large-format loudspeaker designed for scale, projection, and control. Built around oversized horns and a high-output bass foundation, it delivers effortless dynamics and clarity in rooms where conventional speakers lose composure.",
      "A dedicated mid-frequency horn and separate high-frequency horn sit above a dual 15-inch bass cabinet, forming a true 3-way system. The large horn profiles allow sound to couple naturally to the room, preserving impact, presence, and spatial stability even at elevated listening levels.",
      "The bass enclosure is heavily braced and tuned for control rather than bloom, providing weight and authority without slowing the system down. A carefully voiced 3-way crossover integrates all sections seamlessly, maintaining balance as volume increases.",
      "Thunder is not designed to sound loud.It is designed to remain calm when pushed.",
    ],
    Overview: [
      "True 3-way horn loudspeaker system",
      "Oversized mid and high-frequency horns for controlled directivity",
      "Dedicated dual 15-inch bass cabinet",
      "High-efficiency design suitable for low-power tube or solid-state amplification",
      "Tuned for scale, clarity, and composure at volume",
    ],
    Performance: [
      "Maximum Output: >120 dB peak (room-dependent)",
      "Behavior: Maintains clarity and control at concert-level sound pressure without audible strain",
    ],
    MaterialsFinih: [
      "Baltic birch enclosure with extensive internal bracing",
      "Horns mechanically isolated from bass cabinet",
      "Wood veneer cabinet options",
      "Horns available in custom colors",
    ],
  },
};

