export const productsData = [
  {
    title: "Hush in Silver",
    imageFront: "/images/hush-insilver-front.webp",
    imageSide: "/images/humin-silver-side.jpg",
    price: "₦1,601,600.00",
    soldOut: true,
  },
  {
    title: "Hush in Matte Black",
    imageFront: "/images/hush-in-matte-black.webp",
    imageSide: "/images/hushin-matteblack-side.jpg",
    price: "₦1,601,600.00",
    soldOut: true,
  },
  {
    title: "Hush in Metallic Gray",
    imageFront: "/images/hush-ini-metallic-gray.webp",
    imageSide: "/images/hushin-matallicgray-side.jpg",
    price: "₦1,601,600.00 / Pair",
  },
  {
    title: "Hush in White",
    imageFront: "/images/hush-in-white.webp",
    imageSide: "/images/humin-white-side.jpg",
    price: "₦1,601,600.00 / Pair",
  },
  {
    title: "Hush in Green",
    imageFront: "/images/hush-in-green.webp",
    imageSide: "/images/humin-green-side.jpg",
    price: "₦1,601,600.00 / Pair",
  },
  {
    title: "Hush in Glossy Black",
    imageFront: "/images/hush-in-glosy-black.webp",
    imageSide: "/images/humingloosy-black-side.jpg",
    price: "₦6,135,900.00 / Pair",
  },

  {
    title: "Speakers Cables",
    imageFront: "/images/speaker-cable.webp",
    imageSide: "/images/speakercables-side.jpeg",
    price: "₦160,800.00 / Pair",
  },
  {
    title: "Glow EL34 SET Tube Amp",
    imageFront: "/images/glow-tub-amp.webp",
    imageSide: "/images/glowtube-amp-side.jpg",
    price: "₦2,629,700.00 / Pair",
  },
  {
    title: "Echo",
    imageFront: "/images/echo.webp",
    imageSide: "/images/echo-side.jpg",
    price: "₦37,984,000.00 / Pair",
  },
  {
    title: "Hum in Bruch Aluminum",
    imageFront: "/images/hum-in-brushed.webp",
    imageSide: "/images/humin-brushed-side.jpg",
    price: "₦7,150,600.00 / Pair",
  },
  {
    title: "Hush in Glossy Black",
    imageFront: "/images/hum-in-whit-oak.webp",
    imageSide: "/images/humin-whiteoak-side.jpg",
    price: "₦6,135,900.00 / Pair",
  },
  {
    title: "Hum in Green Edge Plexiglass",
    imageFront: "/images/hum-in-walnut.webp",
    imageSide: "/images/hubin-walnut-side.jpg",
    price: "₦7,304,600.00 ",
  },
  {
    title: "Hum in Bruch Aluminum",
    imageFront: "/images/hum-in-brushed.webp",
    imageSide: "/images/humin-brushed-side.jpg",
    price: "₦7,150,600.00 / Pair",
  },
  {
    title: "Whisper",
    imageFront: "/images/whisper.webp",
    imageSide: "/images/whisper-side.jpg",
    price: "₦13,148,300.00 / Pair",
  },
  {
    title: "Roar",
    imageFront: "/images/roar.webp",
    imageSide: "/images/roar-side.jpg",
    price: "₦21,913,800.00 / Pair",
  },
  {
    title: "Thunder",
    imageFront: "/images/thunder.webp",
    imageSide: "/images/thunder-side.jpg",
    price: "₦124,17,200.00 / Pair",
  },
];