export const productdetailsData = [
  {
    title: "Hush in Silver",
    imageFront: "/images/hush-insilver-front.webp",
    imageSide: "/images/humin-silver-side.jpg",
    price: "₦1,601,600.00",
    soldOut: true,
    href: "hushinsilver",
  },
  {
    title: "Hush in Matte Black",
    imageFront: "/images/hush-in-matte-black.webp",
    imageSide: "/images/hushin-matteblack-side.jpg",
    price: "₦1,601,600.00",
    soldOut: true,
    href: "hush-in-matte-black",
  },
  {
    title: "Hush in Metallic Gray",
    imageFront: "/images/hush-ini-metallic-gray.webp",
    imageSide: "/images/hushin-matallicgray-side.jpg",
    price: "₦1,601,600.00 / Pair",
    href: "hush-in-metallic-gray",
  },
  {
    title: "Hush in White",
    imageFront: "/images/hush-in-white.webp",
    imageSide: "/images/humin-white-side.jpg",
    price: "₦1,601,600.00 / Pair",
    href: "hush-in-white",
  },
  {
    title: "Hush in Green",
    imageFront: "/images/hush-in-green.webp",
    imageSide: "/images/humin-green-side.jpg",
    price: "₦1,601,600.00 / Pair",
    href: "hush-in-green",
  },
  {
    title: "Hush in Glossy Black",
    imageFront: "/images/hush-in-glosy-black.webp",
    imageSide: "/images/humingloosy-black-side.jpg",
    price: "₦6,135,900.00 / Pair",
    href: "hush-in-glossy-black",
  },
  {
    title: "Speakers Cables",
    imageFront: "/images/speaker-cable.webp",
    imageSide: "/images/speakercables-side.jpeg",
    price: "₦160,800.00 / Pair",
    href: "speakers-cables",
  },
  {
    title: "Glow EL34 SET Tube Amp",
    imageFront: "/images/glow-tub-amp.webp",
    imageSide: "/images/glowtube-amp-side.jpg",
    price: "₦2,629,700.00 / Pair",
    href: "glow-el34-set-tube-amp",
  },
  {
    title: "Echo",
    imageFront: "/images/echo.webp",
    imageSide: "/images/echo-side.jpg",
    price: "₦37,984,000.00 / Pair",
    href: "echo",
  },
  {
    title: "Hum in Bruch Aluminum",
    imageFront: "/images/hum-in-brushed.webp",
    imageSide: "/images/humin-brushed-side.jpg",
    price: "₦7,150,600.00 / Pair",
    href: "hum-in-brush-aluminum",
  },
  {
    title: "Hum in White Oak",
    imageFront: "/images/hum-in-whit-oak.webp",
    imageSide: "/images/humin-whiteoak-side.jpg",
    price: "₦6,103,200.00 / Pair",
    href: "hum-in-brush-aluminum",
  },
  {
    title: "Hush in Walnut",
    imageFront: "/images/hum-in-walnut.webp",
    imageSide: "images/hubin-walnut-side.jpg",
    price: "₦6,135,900.00 / Pair",
    href: "hush-in-white-oak",
  },
  {
    title: "Hum in Green Edge Plexiglass",
    imageFront: "/images/hum-in-green-edge.webp",
    imageSide: "/images/humin-greenedge-side.jpg",
    price: "₦7,304,600.00",
    href: "hum-in-green-edge-plexiglass",
  },

  {
    title: "Whisper",
    imageFront: "/images/whisper.webp",
    imageSide: "/images/whisper-side.jpg",
    price: "₦13,148,300.00 / Pair",
    href: "whisper",
  },
  {
    title: "Roar",
    imageFront: "/images/roar.webp",
    imageSide: "/images/roar-side.jpg",
    price: "₦21,913,800.00 / Pair",
    href: "roar",
  },
  {
    title: "Thunder",
    imageFront: "/images/thunder.webp",
    imageSide: "/images/thunder-side.jpg",
    price: "₦124,17,200.00 / Pair",
    href: "thunder",
  },
];
